version: '2'

services:
  db:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mytestdb
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    depends_on:
      - db
    ports:
      - 15672:15672
      - 5672:5672
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        JAR_FILE: target/twilio-example-1.0-SNAPSHOT.jar
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - DB_URL=jdbc:postgresql://db;

  ngrok:
    container_name: ngrok
    ports:
      - 4040:4040
    image: wernight/ngrok
    depends_on:
      - app
    environment:
      - NGROK_AUTH=3JRscVAAMKiTudDQKNG1A_3wBr3oRcfbtpeH1qFpEsq
      - NGROK_PORT=app:8080